//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tblQuestion
    {
        public int QuestionID { get; set; }
        public int QuizID { get; set; }
        [Required]
        public string QuestionText { get; set; }
        [Required]
        public string Option1 { get; set; }
        [Required]
        public string Option2 { get; set; }
        [Required]
        public string Option3 { get; set; }
        public string Option4 { get; set; }
        public string Option5 { get; set; }
        [Required]
        public string CorrectAnswer { get; set; }
    
        public virtual tlkpQuiz tlkpQuiz { get; set; }
    }
}
